// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVPOq4fLflmbpBv0bCr-pBADI2ESb9Ko',
    appId: '1:615387534431:web:dadfd30c14f0f700dcf7ea',
    messagingSenderId: '615387534431',
    projectId: 'fir-getx-app-b76a5',
    authDomain: 'fir-getx-app-b76a5.firebaseapp.com',
    databaseURL: 'https://fir-getx-app-b76a5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-getx-app-b76a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlnX1y8NUMX6Lw2Y2I8hvRocqk5mj6dg',
    appId: '1:615387534431:android:1ab94810f0217af6dcf7ea',
    messagingSenderId: '615387534431',
    projectId: 'fir-getx-app-b76a5',
    databaseURL: 'https://fir-getx-app-b76a5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-getx-app-b76a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQ3zGXrQOpXtjsPVLM4s6gI-GMTISo6o',
    appId: '1:615387534431:ios:d2136e0b54844315dcf7ea',
    messagingSenderId: '615387534431',
    projectId: 'fir-getx-app-b76a5',
    databaseURL: 'https://fir-getx-app-b76a5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-getx-app-b76a5.appspot.com',
    androidClientId: '615387534431-hftja012rnrcd5q2156at41p9tnk6uun.apps.googleusercontent.com',
    iosClientId: '615387534431-c5bj28jqor9sjlmmia0dmgilcveeegns.apps.googleusercontent.com',
    iosBundleId: 'com.example.assigmentProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQ3zGXrQOpXtjsPVLM4s6gI-GMTISo6o',
    appId: '1:615387534431:ios:d7f01a4765105bbcdcf7ea',
    messagingSenderId: '615387534431',
    projectId: 'fir-getx-app-b76a5',
    databaseURL: 'https://fir-getx-app-b76a5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-getx-app-b76a5.appspot.com',
    androidClientId: '615387534431-hftja012rnrcd5q2156at41p9tnk6uun.apps.googleusercontent.com',
    iosClientId: '615387534431-p7iiipo2rghisgjittt1u69an88agi66.apps.googleusercontent.com',
    iosBundleId: 'com.example.assigmentProject.RunnerTests',
  );
}
